import React from "react";
import "./Nutrition.css";
import { Link } from "react-router-dom";
import Predictor from "./Predictor/Predictor";
import nutrition from "./../../../Assets/icons/nutrition.png";
import Workout from "./../../../Assets/icons/trainer (4).png";
import Ask from "./../../../Assets/icons/conversation.png";
import Calories from "./../../../Assets/icons/calories-calculator.png";
import BMi from "./../../../Assets/icons/bmi.png";
import Food from "./../../../Assets/icons/calories.png";
import { MdOutlineArrowForwardIos } from "react-icons/md";

const Nutrition = () => {
  return (
    <div className="Nutrition-container">
      <h1>Eat well live better </h1>
      <p>
        Join us on a journey to rediscover the joy of healthy eating and
        transform your life
      </p>
      <div className="nutritionM">
        <div className="nutrition-option">
          <div className="nutrition-overlay"></div>
          <h2>Nutrition Plan</h2>
          <h3>
            Personalized diet plans tailored by AI to fit your unique
            nutritional needs.
          </h3>
          <img src={nutrition} alt="" />
          <Link to="/Model" className="link-button">
            Check out
            <MdOutlineArrowForwardIos />
          </Link>
        </div>
        {/* <div className="nutrition-option">
          <div className="nutrition-overlay"></div>
          <h2>Workout Plan</h2>
          <h3>
            Custom workout routines generated by AI to match your fitness goals.
          </h3>

          <img src={Workout} alt="" />
          <Link to="/Model" className="link-button">
            Check out
            <MdOutlineArrowForwardIos />
          </Link>
        </div> */}
        <div className="nutrition-option">
          <div className="nutrition-overlay"></div>
          <h2>Ask Anything</h2>
          <h3>
            Get instant, AI-powered answers to your health and fitness
            questions.
          </h3>

          <img src={Ask} alt="" />
          <Link to="/Model" className="link-button">
            Check out
            <MdOutlineArrowForwardIos />
          </Link>
        </div>
        <div className="nutrition-option">
          <div className="nutrition-overlay"></div>
          <h2>Calories Calculator</h2>
          <h3>
            Easily track your daily caloric intake to manage your diet
            effectively.
          </h3>

          <img src={Calories} alt="" />
          <Link to="/CaloriesCalculator" className="link-button">
            Check out
            <MdOutlineArrowForwardIos />
          </Link>
        </div>
        <div className="nutrition-option">
          <div className="nutrition-overlay"></div>
          <h2>BMI Calculator</h2>
          <h3>
            Quickly calculate your Body Mass Index to understand your body
            better.
          </h3>

          <img src={BMi} alt="" />
          <Link to="/BMI" className="link-button">
            Check out
            <MdOutlineArrowForwardIos />
          </Link>
        </div>
        <div className="nutrition-option">
          <div className="nutrition-overlay"></div>
          <h2>Food Nutritional Details</h2>
          <h3>
            Learn about the nutritional values of your meals to make informed
            eating choices.
          </h3>{" "}
          <img src={Food} alt="" />
          <Link to="/Food" className="link-button">
            Check out
            <MdOutlineArrowForwardIos />
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Nutrition;
